In [1]:
#example 5-3

import pandas as pd
from sklearn.linear_model import LogisticRegression
from sklearn.preprocessing import StandardScaler

df = pd.read_excel(r'data\machine-spec.xlsx')
with pd.option_context('display.max_rows', 6): display(df)

x = df[['machine_age_months', 'operate_hours_per_day']]
y = df['machine_meets_spec']

scaler = StandardScaler()
x = scaler.fit_transform(x)

model = LogisticRegression()
model.fit(x, y)

x_predict = [[30, 6], [40, 8], [50, 5], [60, 3]]
#ข้อมูลที่จะทำนายผล ก็ต้องปรับสเกลเช่นเดียวกัน
x_predict_sc = scaler.transform(x_predict)  
y_predict = model.predict(x_predict_sc)

print('Prediction:')
for (i, xp) in enumerate(x_predict):
    #คอลัมน์ผลลัพธ์มีค่าเป็น 0/1 จึงเทียบเป็นสตริงที่เข้าใจได้
    mp = 'No' if y_predict[i] == 0 else 'Yes'
    
    t = f'Machine Age: {xp[0]} Month(s), '
    t += f'Operate: {xp[1]} Hour(s)/Day '
    t += f'=> Meet Spec: {mp}'
    print(t)

print()
print('Logistic Function:') 
ic = '{:.2f}'.format(model.intercept_[0])
ce1 = '{:.2f}'.format(model.coef_[0, 0])
ce2 = '{:.2f}'.format(model.coef_[0, 1])

print(f'P(x) = 1 / (1 + exp({ic} + ({ce1})age + ({ce2})hour))')

    machine_age_months  operate_hours_per_day  machine_meets_spec
0                   57                      4                   1
1                   73                      5                   0
2                   22                      5                   1
..                 ...                    ...                 ...
17                  71                      7                   0
18                  35                      4                   0
19                  44                      5                   1

[20 rows x 3 columns]

Prediction:
Machine Age: 30 Month(s), Operate: 6 Hour(s)/Day => Meet Spec: Yes
Machine Age: 40 Month(s), Operate: 8 Hour(s)/Day => Meet Spec: No
Machine Age: 50 Month(s), Operate: 5 Hour(s)/Day => Meet Spec: No
Machine Age: 60 Month(s), Operate: 3 Hour(s)/Day => Meet Spec: Yes

Logistic Function:
P(x) = 1 / (1 + exp(-0.14 + (-1.16)age + (-0.98)hour))

C:\Users\User\AppData\Local\Programs\Python\Python313\Lib\site-packages\sklearn\base.py:493: UserWarning: X does not have valid feature names, but StandardScaler was fitted with feature names
  warnings.warn(