In [25]:
#example 5-4

import pandas as pd
from sklearn.linear_model import LogisticRegression
from sklearn.preprocessing import LabelEncoder
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split

df = pd.read_excel(r'data\reptile.xlsx')
with pd.option_context('display.max_rows', 6): display(df)

#ข้อมูลในคอลัมน์ water เป็นสตริง ต้องเข้ารหัสเป็นตัวเลข
encoder = LabelEncoder()
df['water'] = encoder.fit_transform(df['water'])

features = ['temperature', 'water']
x = df[features]
y = df['gender']

x_train, x_test, y_train, y_test = train_test_split(x, y, random_state=0)

#ปรับสเกลให้คอลัมน์ temperature และ water มีค่าใกล้เคียงกัน 
#scaling after splitting
scaler = StandardScaler()
x_train = scaler.fit_transform(x_train)
x_test = scaler.transform(x_test)

model = LogisticRegression()
model.fit(x_train, y_train)

#กำหนดข้อมูลสำหรับทำนายผล
tem = 23
water = 'Yes' 
water_enc = encoder.transform([water]) #ต้องเข้ารหัสเช่นเดียวกัน
print(water_enc)

x_pred =  [[tem, water_enc[0]]]
x_pred_sc = scaler.transform(x_pred)  #ต้องปรับสเกลเช่นเดียวกัน
y_pred = model.predict(x_pred_sc)

print('Prediction:')
#แปลงจากตัวเลขเป็นสตริงที่เข้าใจได้ เพื่อการแสดงผล
inv_water_enc = encoder.inverse_transform(water_enc)
print(f'Temperature: {tem}, Water: {inv_water_enc[0]} => Gender: {y_pred[0]}')

print()
print('Logistic Function:')
ic = '{:.2f}'.format(model.intercept_[0])
ce1 = '{:.2f}'.format(model.coef_[0, 0])
ce2 = '{:.2f}'.format(model.coef_[0, 1])

print(f'P(x) = 1 / (1 + exp({ic} + ({ce1})tem + ({ce2})water))')

    temperature water  gender
0            20    No    Male
1            22   Yes    Male
2            22   Yes  Female
..          ...   ...     ...
46           24   Yes  Female
47           22    No    Male
48           24   Yes  Female

[49 rows x 3 columns]

[1]
Prediction:
Temperature: 23, Water: Yes => Gender: Female

Logistic Function:
P(x) = 1 / (1 + exp(0.26 + (-0.75)tem + (-0.25)water))

C:\Users\User\AppData\Local\Programs\Python\Python313\Lib\site-packages\sklearn\base.py:493: UserWarning: X does not have valid feature names, but StandardScaler was fitted with feature names
  warnings.warn(